name: deploy develop
run-name: ${{ github.workflow }} (${{ github.ref_name }} by ${{ github.actor }})
concurrency: ${{ github.workflow }}
on:
  push:
    branches:
      - main
    paths:
      - ref/develop.yaml
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploying to develop"
