name: deploy production mirror
run-name: ${{ github.workflow }} (${{ github.ref_name }} by ${{ github.actor }})
concurrency: ${{ github.workflow }}
on:
  pull_request:
    types:
      - opened
    paths:
      - ref/production.yaml
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploying to production mirror"
